site_name: AIStk — AIS Data Toolkit
site_description: Documentation for the AIStk (AIS data) toolkit
site_url: https://irmina-d.github.io/AIStk
repo_url: https://github.com/irmina-d/AIStk
repo_name: irmina-d/AIStk

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - tables
  - attr_list

plugins:
  - search

nav:
  - Home: index.md
  - Modules:
      - __init__.py: modules/__init__.md
      - cli.py: modules/cli.md
      - core.py: modules/core.md
      - dask_backend.py: modules/dask_backend.md
      - events.py: modules/events.md
      - events_online.py: modules/events_online.md
      - io.py: modules/io.md
      - schema.py: modules/schema.md
      - spark_backend.py: modules/spark_backend.md
      - spatial.py: modules/spatial.md
      - stats.py: modules/stats.md
      - streaming_stats.py: modules/streaming_stats.md
      - utils.py: modules/utils.md
      - viz.py: modules/viz.md
