name: CI

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[viz,cli]"
          pip install "dask[dataframe]" pyarrow shapely h3

      - name: Run tests
        run: pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
