name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            requirements.txt
            pyproject.toml

      - name: Install deps (full)
        run: |
          python -m pip install --upgrade pip
          pip install -e . pytest polars numpy typer
          pip install folium shapely h3 || true
          pip install "dask[complete]" pyspark

      - name: Run tests (pełny)
        env:
          PYTHONPATH: .
          MPLBACKEND: Agg
          ONLINE_TESTS: ${{ secrets.ONLINE_TESTS }}
        run: |
          pytest tests -q
